language: python
sudo: false
cache: pip
python:
  - "3.6"
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - pytest
notifications:
  email:
    on_success: never
    on_failure: always