__title__ = 'LearningPythonBookClub'
__description__ = 'Code examples inspired by Learning Python by Mark Lutz.'
__url__ = 'https://github.com/virtualmadden/Learning.Python.Book.Club'
__version_info__ = ('0', '0', '1')
__version__ = '.'.join(__version_info__)
__author__ = 'Jonathan Madden'
__maintainer__ = 'Jonathan Madden'
__license__ = 'MIT'
__copyright__ = '(c) 2018 by Jonathan Madden'
